[package]
name = "opencc-rs"
version = "0.11.1"
edition = "2021"

[package.metadata.capi]
revision = 0

[dependencies]
clap = "=4.5"
# Exact dependency pins to preserve MSRV (rustc 1.75.0):
# clap_lex@1.0.1, rustc-hash@2.1.1
clap_lex = "=1.0"
rustc-hash = "=2.1.1"

#crc = "=3.3.0"
#time = "=0.3.41"
#time-core = "=0.1.4"

opencc-fmmseg = { git = "https://github.com/laisuk/opencc-fmmseg.git", branch = "master" }
#opencc-fmmseg = { path = "../../../opencc-fmmseg" }
#opencc-fmmseg = "0.11"
opencc-utils = { path = "../../crates/opencc-utils" }

[build-dependencies]
winres = "0.1"
toml = "=0.8"
#indexmap = "=2.11.4"
